logging:
  level:
    root: info
    org.springframework: info
    com.redeyefrog: debug
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss}) %yellow([%thread]) %highlight(%-5level) %logger - %green(%msg%n)"

mock:
  backend:
    url: https://localhost:8443/mock/xml
